# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

# add the evironment variables for container registry: registryName, repositoryName, dockerFolderPath, Application/src/RazorPagesTestSample, and finally a tag that is the github.run_number
env:
  registryName: 'th4kidevopsreg.azurecr.io'
  repositoryName: 'wth/dotnetcoreapp'
  dockerFolderPath: 'Application/src/RazorPagesTestSample'
  tag: ${{ github.run_number }}

on:
  push:
    branches: [ "main" ]
    #only include Application/ path
    paths:
      - 'Application/**'
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    # add working directory to /Application
    defaults:
      run:
        working-directory: Application/
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1
    - name: Restore dependencies
      run: dotnet restore src/RazorPagesTestSample
    - name: Build
      run: dotnet build --no-restore src/RazorPagesTestSample
    - name: Test
      run: dotnet test --no-build --verbosity normal tests/RazorPagesTestSample.Tests

  build-and-push-container:
    # checkout repo
    runs-on: ubuntu-latest
    # depends on build job
    needs: build
    steps:
    - uses: actions/checkout@v2
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ${{ env.dockerFolderPath }}
        push: true
        tags: ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }}
        # add the registry login credentials
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

